# Generated by Django 5.2.6 on 2025-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='MyPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='MyPhoto/'),
        ),
    ]
