# Generated by Django 5.2.6 on 2025-09-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser_myphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='MyPhoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
