# Generated by Django 5.2.6 on 2025-09-17 10:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_myuser_myphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='MyPhoto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Myimage'),
        ),
    ]
